"""super_admin_org_models

Revision ID: 0836e1c65b03
Revises: 95f4e4dd3efb
Create Date: 2026-02-16 15:12:33.175724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0836e1c65b03'
down_revision: Union[str, Sequence[str], None] = '95f4e4dd3efb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_models',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('model_id', sa.Uuid(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['chat_models.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_org_models_model_id'), 'org_models', ['model_id'], unique=False)
    op.create_index(op.f('ix_org_models_org_id'), 'org_models', ['org_id'], unique=False)
    op.add_column('users', sa.Column('is_super_admin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_super_admin')
    op.drop_index(op.f('ix_org_models_org_id'), table_name='org_models')
    op.drop_index(op.f('ix_org_models_model_id'), table_name='org_models')
    op.drop_table('org_models')
    # ### end Alembic commands ###
