"""add config_json to org_provider_configs

Revision ID: 526eeeb8086a
Revises: f3b4c5d6e7f8
Create Date: 2026-02-24 11:45:02.792926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '526eeeb8086a'
down_revision: Union[str, Sequence[str], None] = 'f3b4c5d6e7f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_message_attachments', 'data_base64',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.drop_index(op.f('ix_chat_messages_model_id'), table_name='chat_messages')
    op.create_index(op.f('ix_chat_models_display_order'), 'chat_models', ['display_order'], unique=False)
    op.add_column('org_provider_configs', sa.Column('config_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('orgs', 'web_tools_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('orgs', 'web_search_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('orgs', 'web_scrape_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('orgs', 'web_grounding_openai',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('orgs', 'web_grounding_gemini',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint(op.f('password_resets_token_key'), 'password_resets', type_='unique')
    op.drop_index(op.f('ix_password_resets_token'), table_name='password_resets')
    op.create_index(op.f('ix_password_resets_token'), 'password_resets', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_password_resets_token'), table_name='password_resets')
    op.create_index(op.f('ix_password_resets_token'), 'password_resets', ['token'], unique=False)
    op.create_unique_constraint(op.f('password_resets_token_key'), 'password_resets', ['token'], postgresql_nulls_not_distinct=False)
    op.alter_column('orgs', 'web_grounding_gemini',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('orgs', 'web_grounding_openai',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('orgs', 'web_scrape_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('orgs', 'web_search_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('orgs', 'web_tools_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('org_provider_configs', 'config_json')
    op.drop_index(op.f('ix_chat_models_display_order'), table_name='chat_models')
    op.create_index(op.f('ix_chat_messages_model_id'), 'chat_messages', ['model_id'], unique=False)
    op.alter_column('chat_message_attachments', 'data_base64',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
